name: build winlator orignal version mesa driver 

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      inputMesaVer:
        description: "输入Mesa驱动版本"
        required: true
        default: "mesa-25.1.0"
      inputCustomTag:
        description: "输入customTag"
        required: true
        default: "25.1.0.03.1"

jobs:
  BCC:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: get resources and apply patch
        id: getRes
        run: |
          wget https://github.com/Waim908/BCC/releases/download/wlt-bcc-latest/wlt-bcc.tar.xz || exit 1
          sudo tar xvf wlt-bcc.tar.xz -C /tmp
          cd /tmp/archlinux/bin
          wget https://raw.githubusercontent.com/Waim908/winlator/winlator-custom/.github/workflows/turnip-winlator.sh
          sudo chmod 777 turnip-winlator.sh
          sudo mount --bind /proc archlinux/proc
          sudo mount --bind /sys archlinux/sys
          sudo mount --bind /dev archlinux/dev
          sudo chroot /tmp/archlinux /bin/turnip-winlator.sh ${{ github.event.inputs.inputMesaVer }} ${{ github.event.inputs.inputCustomTag }} || exit 1
          sudo umount -l archlinux/dev
          sudo umount -l archlinux/sys
          sudo umount -l archlinux/proc
          # /tmp/turnip-$2.tzst

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: turnip-${{ github.event.inputs.inputCustomTag }}
          draft: false
          prerelease: false
          tag_name: turnip-${{ github.event.inputs.inputCustomTag }}
          body: |
            Tag => turnip-${{ github.event.inputs.inputCustomTag}}
            Winlator turnip version => turnip-${{ github.event.inputs.inputMesaVer }}
          files: |
            /tmp/archlinux/tmp/turnip-${{ github.event.inputs.inputCustomTag }}.tzst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}